files/topic8/bioweb/bioweb/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.schemas import get_schema_view
from django.views.generic import TemplateView

urlpatterns = [
    path('', include('genedata.urls')),
    path('admin/', admin.site.urls),
    path('apischema/', get_schema_view(title="Genedata",
         description="API for interacting with gene records",
         version="1.0.0"), name='openapi-schema'),
    path('swagger-docs/', TemplateView.as_view(
         template_name='genedata/swagger-docs.html',
         extra_context={'schema_url': 'openapi-schema'}), name='swagger-ui'),
]

files/topic8/bioweb/genedata/urls.py
from django.urls import include, path
from . import views
from . import api

urlpatterns = [
    path('', views.GeneList.as_view(), name='index'),
    path('gene/<int:pk>', views.GeneDetail.as_view(), name='gene'),
    path('list/<str:type>', views.GeneList.as_view(), name='list'),
    path('poslist/', views.GeneList.as_view(), name='poslist'),
    path('create_ec/', views.create_ec, name='create'),
    path('create_gene/', views.GeneCreate.as_view(), name='create_gene'),
    path('delete/<int:pk>', views.GeneDelete.as_view(), name='delete'),
    path('update/<int:pk>', views.GeneUpdate.as_view(), name='update'),
    path('api/genes', api.GeneList.as_view(), name='genes_api'),
    path('api/gene/<int:pk>/', api.GeneDetail.as_view(), name='gene_api'),
    path('app/', views.SPA, name='spa'),
]

files/topic8/bioweb/genedata/models.py
from django.db import models


class EC(models.Model):
    ec_name = models.CharField(max_length=256, null=False, blank=False)

    def __str__(self):
        return self.ec_name


class Sequencing(models.Model):
    sequencing_factory = models.CharField(max_length=256,
                                          null=False, blank=False)
    factory_location = models.CharField(max_length=256,
                                        null=False, blank=False)

    def __str__(self):
        return self.factory_location


class Gene(models.Model):
    gene_id = models.CharField(max_length=256, null=False,
                               blank=False, db_index=True)
    entity = models.CharField(max_length=256, null=False,
                              blank=False)
    start = models.IntegerField(null=False, blank=True)
    stop = models.IntegerField(null=False, blank=True)
    sense = models.CharField(max_length=1)
    start_codon = models.CharField(max_length=1, default="M")
    sequencing = models.ForeignKey(Sequencing, on_delete=models.DO_NOTHING)
    ec = models.ForeignKey(EC, on_delete=models.DO_NOTHING)
    access = models.IntegerField(null=False, blank=False, default=0)

    def __str__(self):
        return self.gene_id


class Product(models.Model):
    type = models.CharField(max_length=256, null=False,
                            blank=False)
    product = models.CharField(max_length=256, null=False, blank=False)
    gene = models.ForeignKey(Gene, on_delete=models.CASCADE)


class Attribute(models.Model):
    key = models.CharField(max_length=256, null=False, blank=False)
    value = models.CharField(max_length=256, null=False, blank=False)
    gene = models.ManyToManyField(Gene, through='GeneAttributeLink')

    def __str__(self):
        return self.key+":"+self.value


class GeneAttributeLink(models.Model):
    gene = models.ForeignKey(Gene, on_delete=models.DO_NOTHING)
    attribute = models.ForeignKey(Attribute, on_delete=models.DO_NOTHING)

files/topic8/bioweb/genedata/forms.py
from django import forms
from django.forms import ModelForm
from .models import *


class ECForm(forms.Form):
    ec_name = forms.CharField(label='EC Name', max_length=100)


class GeneForm(ModelForm):

    def clean(self):
        cleaned_data = super(GeneForm, self).clean()
        entity = cleaned_data.get("entity")
        sense = cleaned_data.get("sense")

        if not entity == "Chromosome" and not entity == "Plasmid":
            raise forms.ValidationError("Entity must be 'Chromosome' or 'Plasmid'")
        if not sense == "+" and not sense == "-":
            raise forms.ValidationError("Sense must be '+' or '-'")
        return(cleaned_data)

    class Meta:
        model = Gene
        fields = ['gene_id', 'entity', 'start', 'stop', 'sense',
                  'start_codon', 'sequencing', 'ec']

files/topic8/bioweb/genedata/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import *
from .forms import *
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import DeleteView
from django.views.generic.edit import UpdateView

def SPA(request):
    return render(request, 'genedata/spa.html')

class GeneList(ListView):
    model = Gene
    context_object_name = 'master_genes'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['master_genes'] = Gene.objects.all()
        if "poslist" in self.request.get_full_path():
            context['genes'] = Gene.objects.filter(entity__exact='Chromosome').filter(sense__startswith='+')
        if 'type' in self.kwargs:
            if "Chromosome" in self.kwargs['type'] or "Plasmid" in self.kwargs['type']:
                context['genes'] = Gene.objects.filter(entity__exact=self.kwargs['type'])
        return context

    def get_template_names(self):
        if "poslist" in self.request.get_full_path():
             return 'genedata/list.html'
        if 'type' in self.kwargs:
            if "Chromosome" in self.kwargs['type'] or "Plasmid" in self.kwargs['type']:
                return 'genedata/list.html'

        return 'genedata/index.html'


class GeneDetail(DetailView):
    model = Gene
    context_object_name = 'gene'
    template_name = 'genedata/gene.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['master_genes'] = Gene.objects.all()
        return context


def poslist(request):
    genes = Gene.objects.filter(entity__exact='Chromosome').filter(sense__startswith='+')
    master_genes = Gene.objects.all()
    return render(request, 'genedata/list.html', {'genes': genes, 'type': 'PosList'})


class GeneDelete(DeleteView):
    model = Gene
    success_url = "/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['master_genes'] = Gene.objects.all()
        return context

class GeneUpdate(UpdateView):
    model = Gene
    fields = fields = ['gene_id', 'entity', 'start', 'stop', 'sense', 'start_codon',
              'sequencing', 'ec']
    template_name_suffix = '_update_form'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['master_genes'] = Gene.objects.all()
        return context

def create_ec(request):
    master_genes = Gene.objects.all()
    if request.method == 'POST':
        form = ECForm(request.POST)
        if form.is_valid():
            ec = EC()
            ec.ec_name = form.cleaned_data['ec_name']
            ec.save()
            return HttpResponseRedirect('/create_ec/')
    else:
        ecs = EC.objects.all()
        form = ECForm()
    return render(request, 'genedata/ec.html', {'form': form, 'ecs': ecs, 'master_genes': master_genes})


class GeneCreate(CreateView):
    model = Gene
    template_name = 'genedata/create_gene.html'
    form_class = GeneForm
    success_url = "/create_gene/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['master_genes'] = Gene.objects.all()
        return context

files/topic8/bioweb/genedata/templates/genedata/base.html
{% include "./header.html" %}
{% include "./title.html" %}

<div class="container-fluid">

<div class="row">
{% block geneList %}
<div class="col-4" id="gene_list">
<h1>D.Bucha Genes</h1>
<table>
  <tr><th>Gene ID</th></tr>
  {% for gene in master_genes %}
      <tr><td><a href="/gene/{{gene.pk}}">{{gene}}</a></td></tr>
  {% endfor %}
</table>
</div>
{% endblock%}

<div  class="col-8" class="content">
  {% block content %}Didn't render content{% endblock %}
</div>
</div>

</div>

{% include "./footer.html" %}

files/topic8/bioweb/genedata/templates/genedata/create_gene.html
{% extends "./base.html" %}
{% load bootstrap4 %}

{% block content %}
<h2>Add New Gene </h2>
<form action="/create_gene/" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Submit">
</form>
{% endblock%}

files/topic8/bioweb/genedata/templates/genedata/ec.html
{% extends "./base.html" %}
{% load bootstrap4 %}

{% block content %}
<h2>Current EC Names</h2>
<table>
  <tr><th>EC Name</th></th>
    {% for ec in ecs %}
      <tr><td>{{ ec }}</td></tr>
    {% endfor %}
</table>

<br />
<h2>Add New EC Name</h2>
<form action="/create_ec/" method="post"  class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="Submit">
</form>
{% endblock%}

files/topic8/bioweb/genedata/templates/genedata/footer.html
{% load my_tags %}
{% load bootstrap4 %}

<div class="container-fluid">
<div class="row">
<div class="col-md-8" id="footer">
    <p>Author: D. Buchan. Date:  {% todays_date %}.</p>
</div>
</div>
</div>
</body>
</html>

files/topic8/bioweb/genedata/templates/genedata/gene.html
{% extends "./base.html" %}
{% load bootstrap4 %}

{% block content %}
    <h1>{{gene}}</h1>
    <table>
      <tr><th>Key</th><th>Value</th></tr>
        <tr><td>Entity: </td><td>{{gene.entity}}</td></tr>
        <tr><td>Start: </td><td>{{gene.start}}</td></tr>
        <tr><td>Stop: </td><td>{{gene.stop}}</td></tr>
        <tr><td>Sense: </td><td>{{gene.sense}}</td></tr>
        <tr><td>Start Codon: </td><td>{{gene.start_codon}}</td></tr>
        {% with seq=gene.sequencing %}
            <tr><td>Sequencing Factory:
            </td><td>{{seq.sequencing_factory}}</td></tr>
            <tr><td>Factory Location: </td><td>{{seq.factory_location}}</td></tr>
        {% endwith %}
        {% with ec=gene.ec %}
            <tr><td>EC Name: </td><td>{{ec.ec_name}}</td></tr>
        {% endwith %}
        {% with links=gene.geneattributelink_set.all %}
           {% for link in links %}
               <tr><td>{{link.attribute.key}}</td><td>{{link.attribute.value}}</td></tr>
             {% endfor %}
         {% endwith %}
    </table>
    <a href="/update/{{gene.pk}}">UPDATE RECORD</a>   <br />
    <a href="/delete/{{gene.pk}}">DELETE RECORD</a>

{% endblock %}

files/topic8/bioweb/genedata/templates/genedata/gene_confirm_delete.html
{% extends "./base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>
{% endblock %}

files/topic8/bioweb/genedata/templates/genedata/gene_update_form.html
{% extends "./base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>
{% endblock %}

files/topic8/bioweb/genedata/templates/genedata/header.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="Toy Gene data website">
    <meta name="keywords" content="HTML,gene,genes,advanced,web,development">
    <meta name="author" content="D.Buchan">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" type="text/css" href="../static/css/genedata.css">
    <script>
      function exampleFunction() {
      var x, y, z;
      x = 5;
      y = 6.6;
      z = "hello";
      x = x + y * 2;
      // alert(x);
      console.log(z);
      var test_array = [1,2,3];
      var test_hash = {"one": 2, "two": 'this'};
      while(true){
        console.log("while loop");
        break;
      };
      for (i = 0; i < test_array.length; i++) {
        console.log("array out: "+test_array[i]);
      }
      if(test_array.length === 3)
      {
        console.log("array is the right length");
      }
      test_array.forEach(function(element){
         console.log("For Each Output: "+element)
      });
      }
      //exampleFunction();
      function changePage() {
        console.log('Changing Page');
        var h1_elements = document.querySelectorAll("h1");
        for(h in h1_elements) {
           h1_elements[h].innerHTML = 'Organism Name: D. Bucheria';
        };
        var list_panel = document.getElementById("gene_list");
        list_panel.innerHTML = "<h2>Oooops, they're gone</h2>";
        var nav_links = document.getElementsByClassName("nav_link");
        for (var i = 0; i < nav_links.length; i++) {
          nav_links[i].style.color = "black";
        }
      };
    </script>
</head>
<body>

files/topic8/bioweb/genedata/templates/genedata/index.html
{% extends "./base.html" %}

{% block content %}
    <h2>Select gene location</h2>
    <a href="/list/Chromosome">Chromosome</a> OR <a href="/list/Plasmid">Plasmid</a>
    <h2>Show Positive Chromosome</h2>
    <a href="/poslist/">Show This List</a>
    <h2>Create EC Entry</h2>
    <a href="/create_ec/">Add a EC Entry</a>
    <h2>Create Gene Entry</h2>
    <a href="/create_gene/">Add Gene Entry To DB</a>
    <br />
{% endblock %}

files/topic8/bioweb/genedata/templates/genedata/list.html
{% extends "./base.html" %}
{% load bootstrap4 %}

{% block content %}
    <h1>Filtered List: {{type}}</h1>
    <table>
      <tr><th>Gene ID</th></tr>
      {% for gene in genes %}
      <tr><td><a href="/gene/{{gene.pk}}">{{gene}}</a></td></tr>
      {% endfor %}
    </table>
{% endblock %}

files/topic8/bioweb/genedata/templates/genedata/master.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
    <meta name="description" content="Toy Gene data website">
    <meta name="keywords" content="HTML,gene,genes,advanced,web,development">
    <meta name="author" content="D.Buchan">
</head>
<body>
      <div id="header">
        <img src="https://upload.wikimedia.org/wikipedia/commons/e/e0/202002_Laboratory_instrument_dna.svg" alt="dna logo" width="50px" height="50px">
        <h1>Gene Browser</h2>
      </div>
      <div id="navigation">
         <a href="/">Home</a>
      </div>
      <div id="content">
          <p>This is some holder content before we develop the application</p>
      </div>
      <div id="footer">
          <p>Author: D. Buchan. Date: 23rd April.</p>
      </div>
</body>
</html>

files/topic8/bioweb/genedata/templates/genedata/spa.html
{% load bootstrap4 %}
{% load my_tags %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="description" content="Toy Gene data website">
    <meta name="keywords" content="HTML,gene,genes,advanced,web,development">
    <meta name="author" content="D.Buchan">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" type="text/css" href="../static/css/genedata.css">
    <script src="../static/js/spa.js"></script>
  </head>
  <body onload="initialisePage()">

  <nav class="navbar navbar-expand-md sticky-top flex-column">
     <div class="w-100 d-flex">
       <div class="navbar-header" id="header">
          <img src="https://upload.wikimedia.org/wikipedia/commons/e/e0/202002_Laboratory_instrument_dna.svg" id="logo" alt="dna logo">
          <h1 id="application_title">Gene Browser</h1>
      </div>
    </div>
    <div class="w-100 d-flex">
      <ul class="navbar-nav mr-auto" id="navigation">
         <li class="nav-item active">
          <a class="nav-link" href="javascript:void(0);" onClick="writeInitialContent();">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
          <a class="nav-link" href="https://www.ebi.ac.uk/">EBI <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
         <a class="nav-link" href="https://www.uniprot.org/">Uniprot <span class="sr-only">(current)</span></a>
         </li>
      </ul>
    </div>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-4" id="gene_list">
        <h1>D.Bucha Genes</h1>
              <div id="gene_table">NO TABLE</div>
      </div>

      <div class="col-sm-8" id="content">
        <div id="dynamic_content">NO CONTENT</div>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row">
        <div class="col-md-8" id="footer">
          <hr>
          <p>Author: D. Buchan. Date: {% todays_date %}
        </div>
    </div>
  </div>
    </body>
  </html>

files/topic8/bioweb/genedata/templates/genedata/swagger-docs.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script>
    const ui = SwaggerUIBundle({
        url: "{% url schema_url %}",
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout",
        requestInterceptor: (request) => {
          request.headers['X-CSRFToken'] = "{{ csrf_token }}"
          return request;
        }
      })
    </script>
  </body>
</html>

files/topic8/bioweb/genedata/templates/genedata/title.html
<nav class="navbar navbar-expand-md sticky-top flex-column">
  <div class="w-100 d-flex">
    <div class="navbar-header" id="header">
      <img src="https://upload.wikimedia.org/wikipedia/commons/e/e0/202002_Laboratory_instrument_dna.svg"  id="logo"  alt="dna logo" width="50px" height="50px">
      <h1 id="application_title">Gene Browser</h2>
    </div>
  </div>

  <div class="w-100 d-flex">
   <ul class="navbar-nav mr-auto" id="navigation">
      <li class="nav-item active">
       <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
       </li>
       <li class="nav-item active">
       <a class="nav-link" href="https://www.ebi.ac.uk/">EBI <span class="sr-only">(current)</span></a>
       </li>
       <li class="nav-item active">
      <a class="nav-link" href="https://www.uniprot.org/">Uniprot <span class="sr-only">(current)</span></a>
      </li>
   </ul>
   </div>
</nav>